version: '3.1'

services:

  php:
    image: trafex/alpine-nginx-php7:1.2.0
    container_name: php-app
    ports:
      - '8080:8080'
    volumes:
      - ./my-codebase:/var/www/html
    environment:    
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_DATABASE_SERVER_HOST}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql
    networks:
      - back-end

  mysql:
    image: mysql:5.7
    container_name: db-server
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - back-end
    ports:
      - 3306:3306 # for MySQL Workbench Host is 127.0.0.1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.5
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=${MYSQL_DATABASE_SERVER_HOST} # name of MySQL service
      - MYSQL_ROOT_PASSWORD=${MYSQL_PMA_PASSWORD}
    depends_on:
      - mysql
    networks:
      - back-end    
 
volumes:
  db_volume:
    driver: local

networks:
  back-end:
    driver: bridge
