version: '3'

services:

  # PHP app
  php:
    image: trafex/alpine-nginx-php7:1.2.0
    container_name: php-app
    ports:
      - '8080:8080'
    volumes:
      - ./my-codebase:/var/www/html
    environment:    
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_DATABASE_SERVER_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    networks:
      - my-network

  # database server
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - my-network
    ports:
      - '3306:3306' # optional for MySQL GUI tools host is 127.0.0.1
    # command: mysqld --character_set_server=utf8mb4

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.5 
    container_name: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: ${MYSQL_DATABASE_SERVER_HOST} # name of MySQL service
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

# persistent volume for database
volumes:
  mysql_data:
      driver: local
